version: '3'
services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:stable
    volumes:
      - config:/config
    environment:
      - TZ=Europe/Amsterdam
    restart: always
    network_mode: host
  